server:
  port: 8083
service:
  weather:
    base-url: https://api.openweathermap.org/data/2.5/weather?
    app-id: e02e39bb549cd2bdddb3d2d2c8b2cd04
okta:
  oauth2:
    issuer: https://dev-jmmmssul0t3rz4el.us.auth0.com/
    client-id: mVY72dqPEsrfnwx50ScDRwjUOcZItQF4
    client-secret: YOUR_CLIENT_SECRET

spring:
  datasource:
    url: jdbc:h2:mem:weatherdb
    driverClassName: org.h2.Driver
    username: sa
    password: 12345
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

